language: rust
sudo: required
dist: trusty

cache:
  directories:
  - ~/llvm

matrix:
  include:
    - os: linux
      rust: nightly
#    - os: osx
#      rust: nightly

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./build_linux.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        brew config;
        brew update;
        brew install -v https://raw.githubusercontent.com/Homebrew/homebrew-versions/master/llvm38.rb; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export LIBCLANG_STATIC_PATH=~/clang/lib; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export LLVM_CONFIG_PATH=/usr/local/bin/llvm-config-3.8; export LIBCLANG_STATIC_PATH=`/usr/local/bin/llvm-config-3.8 --libdir`; fi
  - cargo build --verbose
  - RUST_TEST_THREADS=1 cargo test --verbose
