[package]
name = "cpp-codegen-rs"
version = "0.1.0"
authors = ["Jupp Müller <jupp0r@gmail.com>"]

[dependencies]
serde = "*"
serde_json = "*"
serde_macros = "*"
clap = "*"

[dependencies.clang]
version = "*"
features = ["clang_3_8", "static"]

[dependencies.clang-sys]
version = "*"
features = ["clang_3_8", "static"]

[dependencies.handlebars]
version = "*"
features = ["serde_type"]
